### ISSUE TITLE
SyntaxError: illegal target for annotation

### ISSUE THREAD

**Issue by prathameshparit** [camenduru/text-generation-webui-colab#12]
actually I am trying to run in on kaggle but it's giving me this error can somebody help me out

```
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
cab6f1|OK  |    14KiB/s|/content/text-generation-webui/models/pyg-13b-4bit-128g/tokenizer_config.json

Status Legend:
(OK):download completed.
[#846e7e 6.7GiB/6.9GiB(96%) CN:16 DL:233MiB]0m]m
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
846e7e|OK  |   226MiB/s|/content/text-generation-webui/models/pyg-13b-4bit-128g/4bit-128g.safetensors

Status Legend:
(OK):download completed.
/content/text-generation-webui
Gradio HTTP request redirected to localhost :)
Traceback (most recent call last):
  File "/content/text-generation-webui/server.py", line 43, in <module>
    import modules.extensions as extensions_module
  File "/content/text-generation-webui/modules/extensions.py", line 6, in <module>
    import extensions
  File "/opt/conda/lib/python3.10/site-packages/extensions/__init__.py", line 7
    "bufferView": 5,
    ^^^^^^^^^^^^
SyntaxError: illegal target for annotation
```

**Comment by camenduru** [comment]
thanks for the info @prathameshparit ❤ please try again
