### ISSUE TITLE
[Bug]: ERROR:Task exception was never retrieved

### ISSUE THREAD

**Issue by Cabel7** [camenduru/text-generation-webui-colab#16]
Why am I getting this error though.
No model is loading when I try to in the Webui 

WARNING:The gradio "share link" feature downloads a proprietary and unaudited blob to create a reverse tunnel. This is potentially dangerous.
bin /opt/conda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
INFO:Loading stable-vicuna-13B-GPTQ...
INFO:Found the following quantized model: models/stable-vicuna-13B-GPTQ/stable-vicuna-13B-GPTQ-4bit.compat.no-act-order.safetensors
INFO:Using the following device map for the quantized model:
INFO:Loaded the model in 55.13 seconds.
INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://f1bdbcf1f947d12f33.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
INFO:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
ERROR:Task exception was never retrieved
future: <Task finished name='64ppr2666p8_90' coro=<Queue.process_events() done, defined at /opt/conda/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 90, 'data': ...on_hash': '64ppr2666p8'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing>
Traceback (most recent call last):
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 90, 'data': ...on_hash': '64ppr2666p8'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing

**Comment by G-AshwinKumar** [comment]
Have a similar issue as well 

2023-07-13 09:26:32 ERROR:Task exception was never retrieved
future: <Task finished name='sx8c68xlk2c_171' coro=<Queue.process_events() done, defined at /usr/local/lib/python3.10/dist-packages/gradio/queueing.py:343> exception=ValidationError(model='PredictBody', errors=[{'loc': ('data',), 'msg': 'field required', 'type': 'value_error.missing'}])>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PredictBody
data
  field required (type=value_error.missing)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
  File "/content/text-generation-webui/modules/chat.py", line 304, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "/content/text-generation-webui/modules/chat.py", line 289, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "/content/text-generation-webui/modules/chat.py", line 172, in chatbot_wrapper
    stopping_strings = get_stopping_strings(state)
  File "/content/text-generation-webui/modules/chat.py", line 135, in get_stopping_strings
    state['turn_template'].split('<|user-message|>')[1].split('<|bot|>')[0] + '<|bot|>',
IndexError: list index out of range

Happens in multiple notebooks for example in oasst-llama13b-GPTQ-4bit-128g, koala-13B-GPTQ-4bit-128g, gpt4-x-alpaca-13b-native-4bit-128g,vicuna-13B-1.1-GPTQ-4bit-128g

**Comment by Cabel7** [comment]
@G-AshwinKumar
Please use gradio>=3.36.1
And try again

I'm closing this issue since it has been resolved.

**Comment by dragos240** [comment]
The gpt4-x-alpaca-13b-native-4bit-128g [notebook](https://github.com/camenduru/text-generation-webui-colab/blob/main/gpt4-x-alpaca-13b-native-4bit-128g.ipynb), which has this issue is using 3.28.3. It may be good to update that notebook (and others affected by this problem)

EDIT: I reran this with your suggested version and now I'm getting JS related errors in my browser upon clicking generate, which seems to do nothing in the UI as if I didn't click Generate:
```
Uncaught (in promise) TypeError: A is undefined
    U index.js:394
    me Blocks-adc2d4ca.js:49
    Ne Blocks-adc2d4ca.js:49
    Xo Blocks-adc2d4ca.js:49
    Xo Blocks-adc2d4ca.js:49
    ki lifecycle.js:181
    ki lifecycle.js:181
    S Blocks-adc2d4ca.js:5
    ki lifecycle.js:181
    ki lifecycle.js:181
    S Blocks-adc2d4ca.js:5
    ki lifecycle.js:181
    ki lifecycle.js:181
    S Blocks-adc2d4ca.js:5
    yi lifecycle.js:105
    yi lifecycle.js:104
    Ws Blocks-adc2d4ca.js:5
    sn utils.js:41
    ke Component.js:45
    vn scheduler.js:99
    promise callback*wn scheduler.js:20
    hr Component.js:79
    ctx Component.js:127
    Ee Index.svelte:282
    o Index.svelte:343
    ctx Component.js:126
    fc Blocks-adc2d4ca.js:49
    promise callback*fc/< Blocks-adc2d4ca.js:49
    promise callback*fc Blocks-adc2d4ca.js:49
    et Component.js:123
```

EDIT 2: Found a fix:
- Change the tag to 1.8 instead of 1.7 of text-generation-webui
- Remove the line `!pip install -U gradio==3.28.3`

EDIT 3: Made a copy of the notebook with the above changes [here](https://colab.research.google.com/drive/1UaNo9C3TPlcdWgtAt66aNw25y2Gx4NRZ?usp=sharing)
