### ISSUE TITLE
Task exception was never retrieved

### ISSUE THREAD

**Issue by asd519020** [camenduru/text-generation-webui-colab#25]
2023-08-21 06:16:14 ERROR:Task exception was never retrieved
future: <Task finished name='w0d6mwwkndk_173' coro=<Queue.process_events() done, defined at /usr/local/lib/python3.10/dist-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 173, 'data':...on_hash': 'w0d6mwwkndk'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 173, 'data':...on_hash': 'w0d6mwwkndk'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
    
    I use pyg-13b and here is the error.

**Comment by asd519020** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
