### ISSUE TITLE
gptQ 4 Bit does not produce any output on Cloab error: IndexError: list index out of range

### ISSUE THREAD

**Issue by kmkarakaya** [camenduru/text-generation-webui-colab#28]
gptq 4 Bit does not produce any output on Cloab 
error: **IndexError: list index out of range**

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/content/text-generation-webui/modules/chat.py", line 305, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "/content/text-generation-webui/modules/chat.py", line 290, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "/content/text-generation-webui/modules/chat.py", line 194, in chatbot_wrapper
    stopping_strings = get_stopping_strings(state)
  File "/content/text-generation-webui/modules/chat.py", line 161, in get_stopping_strings
    state['turn_template'].split('<|user-message|>')[1].split('<|bot|>')[0] + '<|bot|>',
IndexError: list index out of range

**Comment by camenduru** [comment]
which colab?

**Comment by kmkarakaya** [comment]
free version

**Comment by camenduru** [comment]
is this one `llama-2-13b-chat-GPTQ-4bit (4bit) `
or this one `wizard-lm-uncensored-13b-GPTQ-4bit-128g` ...

**Comment by kmkarakaya** [comment]
this one --> llama-2-13b-chat-GPTQ-4bit (4bit)

**Comment by camenduru** [comment]
please try this 
![Screenshot 2023-08-28 165206](https://github.com/camenduru/text-generation-webui-colab/assets/54370274/7f619737-eb3e-4368-9b03-65836d1207f0)
